# Generated by Django 5.2.1 on 2025-05-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('headers', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(upload_to='templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('placeholders', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', models.JSONField()),
                ('output_format', models.CharField(max_length=10)),
                ('process_all', models.BooleanField(default=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('output_folder', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_generator.datafile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_generator.template')),
            ],
        ),
    ]
