# Generated by Django 5.2.1 on 2025-05-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentgeneration',
            name='output_folder',
        ),
    ]
