# Generated by Django 5.2.1 on 2025-05-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0003_documentgeneration_filename_pattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentgeneration',
            old_name='limit',
            new_name='start_row',
        ),
        migrations.AddField(
            model_name='documentgeneration',
            name='end_row',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
