# Generated by Django 5.2.1 on 2025-05-31 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0004_update_row_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentgeneration',
            name='process_all',
        ),
    ]
