# Generated by Django 5.2.1 on 2025-05-31 20:32

import document_generator.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0005_remove_documentgeneration_process_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='data_file',
            field=models.FileField(upload_to='data/', validators=[document_generator.validators.validate_excel_file_extension]),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_file',
            field=models.FileField(upload_to='templates/', validators=[document_generator.validators.validate_document_file_extension]),
        ),
    ]
